name: perps-turbo-repo

services:
  postgres:
    image: postgres
    container_name: perps-turbo-repo-postgres
    environment:
      POSTGRES_DB: perps-turbo-repo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - perps-turbo-repo_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: perps-turbo-repo-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  perps-turbo-repo_postgres_data:
